// app/(tabs)/global.tsx
import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  ScrollView,
  TouchableOpacity,
  TextInput,
  Text,
  StyleSheet,
  Image,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useAnalysis } from '../../hooks/useAnalysis';
import GradientButton from '../../components/layout/GradientButton';
import ErrorBanner from '../../components/ui/ErrorBanner';
import Colors from '../../constants/Colors';
import mobileAds, {
  BannerAd,
  BannerAdSize,
  TestIds,
  InterstitialAd,
  AdEventType,
} from 'react-native-google-mobile-ads';

const PLANS = ['Free', 'Pro', 'Advanced'] as const;
type Plan = (typeof PLANS)[number];

const DEFAULT_INDICES = [
  'Nifty 50',
  'Nasdaq',
  'S&P 500',
  'Dow Jones',
  'Tesla',
  'Apple',
  'Microsoft',
];

// UPDATED: Removed Pricing Constants to prevent "Fake Paywall" rejection

const BANNER_AD_UNIT_ID = __DEV__
  ? TestIds.BANNER
  : process.env.EXPO_PUBLIC_BANNER_AD_UNIT_ID_GLOBAL || '';

const INTERSTITIAL_AD_UNIT_ID = __DEV__
  ? TestIds.INTERSTITIAL
  : process.env.EXPO_PUBLIC_INTERSTITIAL_AD_UNIT_ID || '';

export default function GlobalScreen() {
  const { analyzeGlobal, loading: analysisLoading } = useAnalysis();
  const router = useRouter();
  const params = useLocalSearchParams();
  const theme = Colors.dark;

  // UPDATED: Default to 'Advanced' to unlock full capabilities immediately
  const [plan, setPlan] = useState<Plan>('Advanced');
  const [marketBadges, setMarketBadges] = useState<string[]>(DEFAULT_INDICES);
  const [inputValue, setInputValue] = useState('');
  const [error, setError] = useState('');
  const [interstitialAd, setInterstitialAd] = useState<InterstitialAd | null>(null);
  const [interstitialLoaded, setInterstitialLoaded] = useState(false);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    mobileAds()
      .initialize()
      .then(() => {
        console.log('AdMob initialized');
      });
  }, []);

  useEffect(() => {
    const ad = InterstitialAd.createForAdRequest(INTERSTITIAL_AD_UNIT_ID, {
      requestNonPersonalizedAdsOnly: true,
    });

    const unsubscribeLoaded = ad.addAdEventListener(AdEventType.LOADED, () => {
      setInterstitialLoaded(true);
    });

    const unsubscribeClosed = ad.addAdEventListener(AdEventType.CLOSED, () => {
      setInterstitialLoaded(false);
      ad.load();
    });

    ad.load();
    setInterstitialAd(ad);

    return () => {
      unsubscribeLoaded();
      unsubscribeClosed();
    };
  }, []);

  useEffect(() => {
    if (
      params.autoGenerate === 'true' &&
      !hasAutoGenerated.current &&
      !analysisLoading &&
      marketBadges.length > 0
    ) {
      console.log('🚀 Auto-generating Intel from notification...');
      hasAutoGenerated.current = true;
      setTimeout(() => {
        handleGenerate();
      }, 300);
    }
  }, [params.autoGenerate, analysisLoading, marketBadges.length]);

  useEffect(() => {
    return () => {
      hasAutoGenerated.current = false;
    };
  }, []);

  const handleAddBadge = () => {
    const trimmed = inputValue.trim();
    if (trimmed && !marketBadges.includes(trimmed)) {
      setMarketBadges([...marketBadges, trimmed]);
      setInputValue('');
    }
  };

  const handleKeyPress = (e: any) => {
    if (e.nativeEvent.key === 'Enter' || inputValue.includes(',')) {
      const cleanValue = inputValue.replace(',', '').trim();
      if (cleanValue && !marketBadges.includes(cleanValue)) {
        setMarketBadges([...marketBadges, cleanValue]);
        setInputValue('');
      }
    }
  };

  const removeBadge = (index: number) => {
    setMarketBadges(marketBadges.filter((_, i) => i !== index));
  };

  const handleGenerate = async () => {
    if (marketBadges.length === 0) {
      setError('Please add at least one market index or stock');
      return;
    }

    setError('');

    if (interstitialLoaded && interstitialAd) {
      interstitialAd.show();
      setTimeout(() => {
        proceedWithAnalysis();
      }, 500);
    } else {
      proceedWithAnalysis();
    }
  };

  const proceedWithAnalysis = async () => {
    try {
      const marketDataString = marketBadges.join(', ');
      
      await analyzeGlobal({
        marketData: marketDataString,
        plan,
      });

      router.push('/result/global');
    } catch (err: any) {
      const message = err?.message || 'Analysis failed. Please try again.';
      setError(message);
    }
  };

  return (
    <SafeAreaView style={[styles.safeArea, { backgroundColor: theme.background }]} edges={['top', 'left', 'right']}>
      <View style={[styles.container, { backgroundColor: theme.background }]}>
        <View style={[styles.header, { backgroundColor: theme.headerBackground }]}>
          <View style={styles.headerLeft}>
            <View style={styles.logoContainer}>
              <Image
                source={require('../../assets/images/logoo.png')}
                style={styles.logoImage}
                resizeMode="contain"
              />
            </View>
            <View>
              <Text style={[styles.headerTitle, { color: theme.text }]}>
                Global Markets
              </Text>
              <Text style={[styles.headerSubtitle, { color: theme.mutedText }]}>
                Market Intelligence
              </Text>
            </View>
          </View>
        </View>

        <View style={styles.main}>
          <ScrollView
            showsVerticalScrollIndicator={false}
            contentContainerStyle={styles.scrollContent}
          >
            {error ? (
              <ErrorBanner message={error} onClose={() => setError('')} />
            ) : null}

            {/* UPDATED: Removed "Select Plan" Card to comply with Policy */}

            <View style={[styles.card, { backgroundColor: theme.cardBackground }]}>
              <View style={styles.cardHeader}>
                <View style={styles.cardHeaderLeft}>
                  <Text style={[styles.cardTitle, { color: theme.text }]}>
                    Market Indices & Stocks
                  </Text>
                  <Text style={[styles.cardSubtitle, { color: theme.mutedText }]}>
                    Add markets to analyze (press Enter after typing)
                  </Text>
                </View>
                <View style={[styles.chip, { backgroundColor: theme.primary }]}>
                  <Text style={[styles.chipText, { color: theme.primaryText }]}>
                    📊 {marketBadges.length}
                  </Text>
                </View>
              </View>

              <View style={styles.badgeContainer}>
                {marketBadges.map((badge, index) => (
                  <View
                    key={index}
                    style={[
                      styles.badge,
                      {
                        backgroundColor: theme.elevatedCard,
                        borderColor: theme.primary,
                      },
                    ]}
                  >
                    <Text style={[styles.badgeText, { color: theme.text }]}>
                      {badge}
                    </Text>
                    <TouchableOpacity
                      onPress={() => removeBadge(index)}
                      style={styles.badgeRemove}
                      activeOpacity={0.6}
                    >
                      <Ionicons name="close-circle" size={18} color={theme.mutedText} />
                    </TouchableOpacity>
                  </View>
                ))}
              </View>

              <TextInput
                style={[
                  styles.badgeInput,
                  {
                    backgroundColor: theme.inputBackground,
                    borderColor: theme.inputBorder,
                    color: theme.text,
                  },
                ]}
                placeholder="Type index/stock name and press Enter"
                placeholderTextColor={theme.mutedText}
                value={inputValue}
                onChangeText={setInputValue}
                onSubmitEditing={handleAddBadge}
                onKeyPress={handleKeyPress}
                returnKeyType="done"
                blurOnSubmit={false}
              />

              <View style={styles.inputFooter}>
                <Text style={[styles.charCount, { color: theme.labelText }]}>
                  💡 Press Enter or comma to add
                </Text>
              </View>
            </View>

            <View
              style={[
                styles.infoCard,
                {
                  backgroundColor: theme.elevatedCard,
                  borderLeftColor: theme.primary,
                },
              ]}
            >
              <Ionicons name="bulb-outline" size={20} color={theme.primary} style={styles.infoIcon} />
              <View style={styles.infoContent}>
                <Text style={[styles.infoTitle, { color: theme.text }]}>
                  Pro Tip
                </Text>
                <Text style={[styles.infoText, { color: theme.mutedText }]}>
                  Add multiple indices, stocks, or currencies for comprehensive global market analysis
                </Text>
              </View>
            </View>
          </ScrollView>

          <View
            style={[
              styles.bottomBar,
              {
                backgroundColor: theme.headerBackground,
                borderTopColor: theme.border,
              },
            ]}
          >
            <GradientButton
              title={analysisLoading ? 'Analyzing Market...' : 'Generate Intel'}
              onPress={handleGenerate}
              disabled={analysisLoading || marketBadges.length === 0}
              loading={analysisLoading}
              size="lg"
            />
          </View>
        </View>

        <View style={styles.bannerContainer}>
          <BannerAd
            unitId={BANNER_AD_UNIT_ID}
            size={BannerAdSize.ANCHORED_ADAPTIVE_BANNER}
            requestOptions={{
              requestNonPersonalizedAdsOnly: true,
            }}
          />
        </View>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoContainer: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  logoImage: {
    width: 44,
    height: 44,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 13,
    fontWeight: '500',
    marginTop: 2,
  },
  bannerContainer: {
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#2E2E3A',
  },
  main: {
    flex: 1,
    flexDirection: 'column',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 8,
  },
  card: {
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  cardHeaderLeft: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  cardSubtitle: {
    fontSize: 13,
    fontWeight: '500',
    marginTop: 4,
    lineHeight: 18,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 14,
    marginLeft: 8,
  },
  chipText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  badgeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 9,
    paddingLeft: 16,
    paddingRight: 12,
    borderRadius: 999,
    borderWidth: 2,
    gap: 8,
  },
  badgeText: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  badgeRemove: {
    padding: 2,
  },
  badgeInput: {
    height: 52,
    borderWidth: 2,
    borderRadius: 16,
    paddingHorizontal: 16,
    fontSize: 15,
    fontWeight: '500',
  },
  inputFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 8,
  },
  charCount: {
    fontSize: 12,
    fontWeight: '600',
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderLeftWidth: 4,
    gap: 12,
  },
  infoIcon: {
    marginTop: 2,
  },
  infoContent: {
    flex: 1,
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
    letterSpacing: -0.2,
  },
  infoText: {
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 19,
  },
  bottomBar: {
    borderTopWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
  },
});